export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_SALE_PROPERTY_BEGIN = 'CREATE_SALE_PROPERTY_BEGIN';
export const CREATE_SALE_PROPERTY_SUCCESS = 'CREATE_SALE_PROPERTY_SUCCESS';
export const CREATE_SALE_PROPERTY_ERROR = 'CREATE_SALE_PROPERTY_ERROR';

export const GET_SALE_PROPERTY_BEGIN = 'GET_SALE_PROPERTY_BEGIN';
export const GET_SALE_PROPERTY_SUCCESS = 'GET_SALE_PROPERTY_SUCCESS';

export const SET_EDIT_SALE_PROPERTY = 'SET_EDIT_SALE_PROPERTY';

export const DELETE_SALE_PROPERTY_BEGIN = 'DELETE_SALE_PROPERTY_BEGIN';
export const DELETE_SALE_PROPERTY_ERROR = 'DELETE_SALE_PROPERTY_ERROR';

export const EDIT_SALE_PROPERTY_BEGIN = 'EDIT_SALE_PROPERTY_BEGIN';
export const EDIT_SALE_PROPERTY_SUCCESS = 'EDIT_SALE_PROPERTY_SUCCESS';
export const EDIT_SALE_PROPERTY_ERROR = 'EDIT_SALE_PROPERTY_ERROR';

// export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
// export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';
// export const CLEAR_FILTERS = 'CLEAR_FILTERS';
// export const CHANGE_PAGE = 'CHANGE_PAGE';

// export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
// export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
